version: '3'

dotenv:
  - docker.env

silent: true

vars:
  service_name: postgres

tasks:
  default:
    cmd: task -l
    desc: List all tasks

  up:
    cmds: 
    - docker compose up -d
    - docker ps
    desc: All docker services are up

  down:
    cmd: docker compose down
    desc: All docker services are down
  
  up:shell:
    cmd: docker compose exec -it {{.service_name}} psql -U ${POSTGRES_USER} ${POSTGRES_DB}
    desc: Connecting with postgres
  
  up:mig:
    cmds:
      - npx prisma ${POSTGRES_DB} push
      - npx prisma generate
    desc: Migrating with a new schema